import { User, Service, Appointment, Review, Notification } from '@/types'

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'patient@healthworld.com',
    name: 'John Patient',
    role: 'patient',
    phone: '+251-911-123456',
    address: 'Bole, Addis Ababa',
    isVerified: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    email: 'doctor@healthworld.com',
    name: 'Dr. Sarah Medical',
    role: 'doctor',
    phone: '+251-911-234567',
    isVerified: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
]

export const mockServices: Service[] = [
  {
    id: '1',
    name: 'Dental Checkup',
    type: 'dental-checkup',
    description: 'Comprehensive dental examination and cleaning at your home',
    price: 1500,
    subscriptionPrice: 5000,
    duration: 60,
    icon: 'UserCheck',
    category: 'Dental Care',
  },
  {
    id: '2',
    name: 'Blood Pressure Monitoring',
    type: 'blood-pressure-monitoring',
    description: 'Regular BP checks with health monitoring and reports',
    price: 500,
    subscriptionPrice: 1500,
    duration: 30,
    icon: 'Activity',
    category: 'Health Monitoring',
  },
  {
    id: '3',
    name: 'Physiotherapy Session',
    type: 'physiotherapy',
    description: 'Professional physiotherapy and rehabilitation at home',
    price: 2000,
    subscriptionPrice: 7000,
    duration: 90,
    icon: 'Heart',
    category: 'Physical Therapy',
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    patientId: '1',
    providerId: '2',
    serviceId: '1',
    date: new Date('2024-11-15T10:00:00'),
    time: '10:00 AM',
    address: 'Bole, Addis Ababa',
    location: { lat: 9.0192, lng: 38.7525 },
    status: 'confirmed',
    isSubscription: false,
    createdAt: new Date('2024-11-05'),
    updatedAt: new Date('2024-11-05'),
  },
  {
    id: '2',
    patientId: '1',
    providerId: '2',
    serviceId: '2',
    date: new Date('2024-11-20T14:00:00'),
    time: '2:00 PM',
    address: 'Bole, Addis Ababa',
    status: 'pending',
    isSubscription: true,
    createdAt: new Date('2024-11-05'),
    updatedAt: new Date('2024-11-05'),
  },
]

export const mockReviews: Review[] = [
  {
    id: '1',
    appointmentId: '1',
    patientId: '1',
    providerId: '2',
    rating: 5,
    comment: 'Excellent service! Very professional and caring.',
    isModerated: true,
    createdAt: new Date('2024-11-06'),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    type: 'appointment-reminder',
    title: 'Appointment Reminder',
    message: 'Your dental checkup is scheduled for tomorrow at 10:00 AM',
    isRead: false,
    actionUrl: '/appointments/1',
    createdAt: new Date('2024-11-05'),
  },
  {
    id: '2',
    userId: '1',
    type: 'health-tip',
    title: 'Daily Health Tip',
    message: 'Remember to stay hydrated! Drink at least 8 glasses of water today.',
    isRead: true,
    createdAt: new Date('2024-11-04'),
  },
]

export interface Hospital {
  id: string
  name: string
  type: 'government' | 'private' | 'specialized'
  address: string
  location: { lat: number; lng: number }
  phone: string
  email: string
  website?: string
  services: string[]
  emergencyAvailable: boolean
  icu: boolean
  ambulance: boolean
  operatingHours: {
    weekdays: string
    weekends: string
    emergency: string
  }
  rating: number
  totalReviews: number
  insurance: string[]
}

export const mockHospitals: Hospital[] = [
  {
    id: '1',
    name: 'St. Paul\'s Hospital Millennium Medical College',
    type: 'government',
    address: 'Gulele Sub City, Addis Ababa',
    location: { lat: 9.0579, lng: 38.7613 },
    phone: '+251-11-551-9222',
    email: 'info@sphmmc.edu.et',
    website: 'http://www.sphmmc.edu.et',
    services: [
      'Emergency Care',
      'Surgery',
      'Cardiology',
      'Neurology',
      'Pediatrics',
      'Maternity',
      'Radiology',
      'Laboratory',
      'Pharmacy',
      'ICU',
      'Dialysis',
      'Cancer Treatment',
    ],
    emergencyAvailable: true,
    icu: true,
    ambulance: true,
    operatingHours: {
      weekdays: '24/7',
      weekends: '24/7',
      emergency: '24/7',
    },
    rating: 4.5,
    totalReviews: 1250,
    insurance: ['EHIA', 'Private Insurance', 'International Insurance'],
  },
  {
    id: '2',
    name: 'Tikur Anbessa Specialized Hospital',
    type: 'government',
    address: 'Lideta Sub City, Addis Ababa',
    location: { lat: 9.0368, lng: 38.7628 },
    phone: '+251-11-551-7700',
    email: 'info@tikuranbessa.org',
    services: [
      'Emergency Care',
      'Surgery',
      'Cardiology',
      'Neurology',
      'Orthopedics',
      'Oncology',
      'Pediatrics',
      'Maternity',
      'Radiology',
      'ICU',
      'Burn Unit',
    ],
    emergencyAvailable: true,
    icu: true,
    ambulance: true,
    operatingHours: {
      weekdays: '24/7',
      weekends: '24/7',
      emergency: '24/7',
    },
    rating: 4.3,
    totalReviews: 2100,
    insurance: ['EHIA', 'Government Insurance', 'Private Insurance'],
  },
  {
    id: '3',
    name: 'Bethel General Hospital',
    type: 'private',
    address: 'Bole Sub City, Addis Ababa',
    location: { lat: 9.0192, lng: 38.7525 },
    phone: '+251-11-661-8822',
    email: 'info@bethelhospital.et',
    website: 'http://www.bethelhospital.et',
    services: [
      'Emergency Care',
      'Surgery',
      'Cardiology',
      'Internal Medicine',
      'Pediatrics',
      'Maternity',
      'Radiology',
      'Laboratory',
      'Pharmacy',
      'ICU',
      'Dental',
    ],
    emergencyAvailable: true,
    icu: true,
    ambulance: true,
    operatingHours: {
      weekdays: '24/7',
      weekends: '24/7',
      emergency: '24/7',
    },
    rating: 4.7,
    totalReviews: 890,
    insurance: ['Private Insurance', 'International Insurance', 'Self-Pay'],
  },
  {
    id: '4',
    name: 'Myungsung Christian Medical Center',
    type: 'private',
    address: 'Addis Ketema Sub City, Addis Ababa',
    location: { lat: 9.0427, lng: 38.7480 },
    phone: '+251-11-557-2299',
    email: 'info@myungsung.org',
    website: 'http://www.myungsung.org',
    services: [
      'Emergency Care',
      'Surgery',
      'Cardiology',
      'Neurology',
      'Orthopedics',
      'Pediatrics',
      'Maternity',
      'Eye Care',
      'Dental',
      'ICU',
    ],
    emergencyAvailable: true,
    icu: true,
    ambulance: true,
    operatingHours: {
      weekdays: '24/7',
      weekends: '24/7',
      emergency: '24/7',
    },
    rating: 4.6,
    totalReviews: 745,
    insurance: ['EHIA', 'Private Insurance', 'International Insurance'],
  },
  {
    id: '5',
    name: 'Hayat Hospital',
    type: 'private',
    address: 'Bole Sub City, Addis Ababa',
    location: { lat: 9.0120, lng: 38.7580 },
    phone: '+251-11-618-7777',
    email: 'info@hayathospital.com',
    website: 'http://www.hayathospital.com',
    services: [
      'Emergency Care',
      'Surgery',
      'Cardiology',
      'Internal Medicine',
      'Pediatrics',
      'Maternity',
      'Radiology',
      'Laboratory',
      'ICU',
    ],
    emergencyAvailable: true,
    icu: true,
    ambulance: true,
    operatingHours: {
      weekdays: '24/7',
      weekends: '24/7',
      emergency: '24/7',
    },
    rating: 4.4,
    totalReviews: 620,
    insurance: ['Private Insurance', 'International Insurance', 'Self-Pay'],
  },
  {
    id: '6',
    name: 'Girum Hospital',
    type: 'private',
    address: 'Kirkos Sub City, Addis Ababa',
    location: { lat: 9.0150, lng: 38.7450 },
    phone: '+251-11-551-5050',
    email: 'info@girumhospital.com',
    services: [
      'Surgery',
      'Internal Medicine',
      'Pediatrics',
      'Maternity',
      'Laboratory',
      'Pharmacy',
      'Dental',
    ],
    emergencyAvailable: false,
    icu: false,
    ambulance: false,
    operatingHours: {
      weekdays: '8:00 AM - 8:00 PM',
      weekends: '9:00 AM - 5:00 PM',
      emergency: 'Not Available',
    },
    rating: 4.2,
    totalReviews: 310,
    insurance: ['Private Insurance', 'Self-Pay'],
  },
  {
    id: '7',
    name: 'Zewditu Memorial Hospital',
    type: 'government',
    address: 'Arada Sub City, Addis Ababa',
    location: { lat: 9.0330, lng: 38.7510 },
    phone: '+251-11-551-6800',
    email: 'info@zewdituhospital.gov.et',
    services: [
      'Emergency Care',
      'Surgery',
      'Internal Medicine',
      'Pediatrics',
      'Maternity',
      'HIV/AIDS Treatment',
      'TB Treatment',
      'Radiology',
      'Laboratory',
    ],
    emergencyAvailable: true,
    icu: true,
    ambulance: true,
    operatingHours: {
      weekdays: '24/7',
      weekends: '24/7',
      emergency: '24/7',
    },
    rating: 4.1,
    totalReviews: 950,
    insurance: ['EHIA', 'Government Insurance'],
  },
  {
    id: '8',
    name: 'Kadisco General Hospital',
    type: 'private',
    address: 'Yeka Sub City, Addis Ababa',
    location: { lat: 9.0480, lng: 38.7850 },
    phone: '+251-11-661-9900',
    email: 'info@kadisco.com',
    website: 'http://www.kadisco.com',
    services: [
      'Emergency Care',
      'Surgery',
      'Orthopedics',
      'Internal Medicine',
      'Pediatrics',
      'Maternity',
      'Eye Care',
      'Dental',
      'Laboratory',
      'ICU',
    ],
    emergencyAvailable: true,
    icu: true,
    ambulance: true,
    operatingHours: {
      weekdays: '24/7',
      weekends: '24/7',
      emergency: '24/7',
    },
    rating: 4.5,
    totalReviews: 580,
    insurance: ['Private Insurance', 'International Insurance', 'Self-Pay'],
  },
]
